# Generated by Django 6.0.2 on 2026-03-06 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_seat_is_available_seat_is_locked_alter_seat_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seat',
            options={'ordering': ['seat_number']},
        ),
    ]
